import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index } from 'typeorm';

/**
 * Logs all AI Manager decisions for review and analytics
 */
@Entity('ai_escalation_logs')
export class AIEscalationLog {
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * The GR task ID this decision was made for
     */
    @Column({ name: 'task_id' })
    @Index()
    taskId: number;

    /**
     * Slack channel where the task lives
     */
    @Column({ name: 'slack_channel', nullable: true })
    slackChannel: string | null;

    /**
     * Event type (e.g., "Guest Complaint", "Noise Complaint")
     */
    @Column({ name: 'event_type', nullable: true })
    eventType: string | null;

    /**
     * AI decision made: SKIP, REMIND, ASK_UPDATE, ESCALATE, AUTO_COMPLETE, AUTO_IN_PROGRESS
     */
    @Column({ name: 'decision' })
    @Index()
    decision: string;

    /**
     * AI mode used: standard, strict, lenient
     */
    @Column({ name: 'ai_mode', default: 'standard' })
    aiMode: string;

    /**
     * The message/reason generated by AI
     */
    @Column({ name: 'message', type: 'text', nullable: true })
    message: string | null;

    /**
     * The reason for the decision (especially for SKIP, AUTO_COMPLETE)
     */
    @Column({ name: 'reason', type: 'text', nullable: true })
    reason: string | null;

    /**
     * Whether the decision was executed successfully
     */
    @Column({ name: 'executed', default: false })
    executed: boolean;

    /**
     * Hours since task was created when decision was made
     */
    @Column({ name: 'hours_since_creation', type: 'float', nullable: true })
    hoursSinceCreation: number | null;

    /**
     * Hours since last human activity when decision was made
     */
    @Column({ name: 'hours_since_last_activity', type: 'float', nullable: true })
    hoursSinceLastActivity: number | null;

    /**
     * Number of previous reminders sent before this decision
     */
    @Column({ name: 'previous_reminder_count', default: 0 })
    previousReminderCount: number;

    /**
     * Custom instructions that were applied (if any)
     */
    @Column({ name: 'custom_instructions', type: 'text', nullable: true })
    customInstructions: string | null;

    /**
     * Context summary (truncated thread for debugging)
     */
    @Column({ name: 'context_summary', type: 'text', nullable: true })
    contextSummary: string | null;

    /**
     * If there was an error during execution
     */
    @Column({ name: 'error', type: 'text', nullable: true })
    error: string | null;

    /**
     * When the decision was made
     */
    @CreateDateColumn({ name: 'created_at' })
    createdAt: Date;
}
