import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index } from 'typeorm';

/**
 * Logs all AI Manager decisions for review and analytics
 */
@Entity('ai_escalation_logs')
export class AIEscalationLog {
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * The GR task ID this decision was made for
     */
    @Column({ name: 'task_id' })
    @Index()
    taskId: number;

    /**
     * Slack channel where the task lives
     */
    @Column({ name: 'slack_channel', nullable: true })
    slackChannel: string | null;

    /**
     * Event type (e.g., "Guest Complaint", "Noise Complaint")
     */
    @Column({ name: 'event_type', nullable: true })
    eventType: string | null;

    /**
     * AI decision made: SKIP, REMIND, ASK_UPDATE, ESCALATE, AUTO_COMPLETE, AUTO_IN_PROGRESS
     */
    @Column({ name: 'decision' })
    @Index()
    decision: string;

    /**
     * AI mode used: standard, strict, lenient
     */
    @Column({ name: 'ai_mode', default: 'standard' })
    aiMode: string;

    /**
     * The message/reason generated by AI
     */
    @Column({ name: 'message', type: 'text', nullable: true })
    message: string | null;

    /**
     * The reason for the decision (especially for SKIP, AUTO_COMPLETE)
     */
    @Column({ name: 'reason', type: 'text', nullable: true })
    reason: string | null;

    @Column({ name: 'severity_level', nullable: true })
    severityLevel: string | null;

    @Column({ name: 'rep_engagement_type', nullable: true })
    repEngagementType: string | null;

    @Column({ name: 'neglect_count', type: 'int', default: 0 })
    neglectCount: number;

    @Column({ name: 'urgency_score', type: 'float', nullable: true })
    urgencyScore: number | null;

    @Column({ name: 'completion_quality', type: 'float', nullable: true })
    completionQuality: number | null;

    @Column({ name: 'recommended_action', nullable: true })
    recommendedAction: string | null;

    @Column({ name: 'next_follow_up_at', type: 'timestamp', nullable: true })
    nextFollowUpAt: Date | null;

    @Column({ name: 'escalation_required', default: false })
    escalationRequired: boolean;

    @Column({ name: 'reasoning_summary', type: 'text', nullable: true })
    reasoningSummary: string | null;

    @Column({ name: 'decision_input_summary', type: 'text', nullable: true })
    decisionInputSummary: string | null;

    @Column({ name: 'decision_payload', type: 'mediumtext', nullable: true })
    decisionPayload: string | null;

    /**
     * Whether the decision was executed successfully
     */
    @Column({ name: 'executed', default: false })
    executed: boolean;

    /**
     * Hours since task was created when decision was made
     */
    @Column({ name: 'hours_since_creation', type: 'float', nullable: true })
    hoursSinceCreation: number | null;

    /**
     * Hours since last human activity when decision was made
     */
    @Column({ name: 'hours_since_last_activity', type: 'float', nullable: true })
    hoursSinceLastActivity: number | null;

    /**
     * Number of previous reminders sent before this decision
     */
    @Column({ name: 'previous_reminder_count', default: 0 })
    previousReminderCount: number;

    /**
     * Custom instructions that were applied (if any)
     */
    @Column({ name: 'custom_instructions', type: 'text', nullable: true })
    customInstructions: string | null;

    /**
     * Context summary (truncated thread for debugging)
     */
    @Column({ name: 'context_summary', type: 'text', nullable: true })
    contextSummary: string | null;

    /**
     * If there was an error during execution
     */
    @Column({ name: 'error', type: 'text', nullable: true })
    error: string | null;

    /**
     * Slack message timestamp (for linking to the AI message)
     */
    @Column({ name: 'slack_message_ts', nullable: true })
    slackMessageTs: string | null;

    /**
     * Slack channel ID for the message
     */
    @Column({ name: 'slack_channel_id', nullable: true })
    slackChannelId: string | null;

    /**
     * Permalink to the Slack message (constructed or fetched)
     */
    @Column({ name: 'slack_permalink', nullable: true })
    slackPermalink: string | null;

    /**
     * Manager feedback on the AI decision
     */
    @Column({ name: 'feedback', type: 'text', nullable: true })
    feedback: string | null;

    /**
     * Feedback rating: positive, negative, or neutral
     */
    @Column({ name: 'feedback_rating', nullable: true })
    feedbackRating: 'positive' | 'negative' | 'neutral' | null;

    /**
     * User ID who provided the feedback
     */
    @Column({ name: 'feedback_by', nullable: true })
    feedbackBy: number | null;

    /**
     * When the feedback was provided
     */
    @Column({ name: 'feedback_at', nullable: true })
    feedbackAt: Date | null;

    @Column({ name: 'feedback_type', nullable: true })
    feedbackType: string | null;

    @Column({ name: 'feedback_scope', nullable: true })
    feedbackScope: string | null;

    @Column({ name: 'expected_behavior', type: 'text', nullable: true })
    expectedBehavior: string | null;

    @Column({ name: 'manager_comment', type: 'text', nullable: true })
    managerComment: string | null;

    /**
     * When the decision was made
     */
    @CreateDateColumn({ name: 'created_at' })
    createdAt: Date;
}
