import { NextFunction, Request, Response } from "express";
import { AIActionItemsTestingService } from "../services/AIActionItemsTestingService";

interface CustomRequest extends Request {
    user?: any;
}

/**
 * TESTING/EXPERIMENTAL controller for action items generated by the new inbox-v2
 * AI chatbot. Fully isolated from the legacy action items and Action Items (Beta)
 * controllers.
 */
export class AIActionItemsTestingController {
    async list(request: Request, response: Response, next: NextFunction) {
        try {
            const { limit, offset, search, channel, propertyName, dateType, startDate, endDate } = request.query as Record<string, string>;
            const data = await new AIActionItemsTestingService().list({
                limit: limit ? Number(limit) : undefined,
                offset: offset ? Number(offset) : undefined,
                search: search || undefined,
                channel: channel || undefined,
                propertyName: propertyName || undefined,
                dateType: dateType || undefined,
                startDate: startDate || undefined,
                endDate: endDate || undefined,
            });
            return response.status(200).json({ status: true, ...data });
        } catch (error) {
            return next(error);
        }
    }

    /**
     * Promote an AI-detected proposal to a real Guest Issue so the standard
     * IssueEditModal (vendor thread, expenses, Slack, timeline) can open it.
     */
    async convertToIssue(request: CustomRequest, response: Response, next: NextFunction) {
        try {
            const detectedItemId = Number(request.params.id);
            if (!detectedItemId || !Number.isFinite(detectedItemId)) {
                return response.status(400).json({ status: false, message: "detected item id required" });
            }
            const userId =
                request.user?.secureStayUserId ??
                request.user?.id ??
                request.user?.uid ??
                "ai-testing";
            const issue = await new AIActionItemsTestingService().convertToIssue(
                detectedItemId,
                String(userId)
            );
            return response.status(200).json({ status: true, data: issue });
        } catch (error: any) {
            if (error?.status === 404) {
                return response.status(404).json({ status: false, message: error.message });
            }
            return next(error);
        }
    }
}
