import { NextFunction, Request, Response } from "express";
import { AIActionItemsTestingService } from "../services/AIActionItemsTestingService";

/**
 * TESTING/EXPERIMENTAL controller for action items generated by the new inbox-v2
 * AI chatbot. Fully isolated from the legacy action items and Action Items (Beta)
 * controllers.
 */
export class AIActionItemsTestingController {
    async list(request: Request, response: Response, next: NextFunction) {
        try {
            const { limit, offset, search, channel } = request.query as Record<string, string>;
            const data = await new AIActionItemsTestingService().list({
                limit: limit ? Number(limit) : undefined,
                offset: offset ? Number(offset) : undefined,
                search: search || undefined,
                channel: channel || undefined,
            });
            return response.status(200).json({ status: true, ...data });
        } catch (error) {
            return next(error);
        }
    }
}
