ALTER TABLE listing_info
  ADD COLUMN IF NOT EXISTS ownerId BIGINT NULL,
  ADD COLUMN IF NOT EXISTS ownerListingTargetId BIGINT NULL,
  ADD COLUMN IF NOT EXISTS ownerContractId BIGINT NULL,
  ADD COLUMN IF NOT EXISTS ownerContractName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS ownerCompanyId BIGINT NULL,
  ADD COLUMN IF NOT EXISTS ownerCompanyName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS hostifyUsersJson LONGTEXT NULL;
