ALTER TABLE upsell_info
  MODIFY COLUMN price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN actualFee DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER price,
  ADD COLUMN pmFee DECIMAL(5,2) NOT NULL DEFAULT 0.00 AFTER actualFee,
  ADD COLUMN processingFee DECIMAL(5,2) NOT NULL DEFAULT 3.00 AFTER pmFee;
