CREATE TABLE IF NOT EXISTS refund_request_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slackTagIds TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdBy VARCHAR(255) NULL,
  updatedBy VARCHAR(255) NULL
);
