CREATE TABLE IF NOT EXISTS action_item_beta_categories (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT NULL,
  color VARCHAR(40) NULL,
  icon VARCHAR(60) NULL,
  notificationTargets JSON NULL,
  isDefault TINYINT(1) NOT NULL DEFAULT 0,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  sortOrder INT NOT NULL DEFAULT 0,
  createdBy VARCHAR(120) NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS action_item_beta_rules (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  description TEXT NULL,
  categoryId CHAR(36) NULL,
  categoryName VARCHAR(120) NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
  sensitivity VARCHAR(20) NOT NULL DEFAULT 'medium',
  autoCreateThreshold FLOAT NOT NULL DEFAULT 0.85,
  reviewThreshold FLOAT NOT NULL DEFAULT 0.65,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  builtIn TINYINT(1) NOT NULL DEFAULT 0,
  triggerPhrases JSON NULL,
  excludePhrases JSON NULL,
  examples JSON NULL,
  negativeExamples JSON NULL,
  instructions TEXT NULL,
  createdBy VARCHAR(120) NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_action_item_beta_rules_categoryId (categoryId)
);

CREATE TABLE IF NOT EXISTS action_item_beta_items (
  id CHAR(36) NOT NULL PRIMARY KEY,
  reservationId INT NULL,
  listingId INT NULL,
  guestName VARCHAR(160) NULL,
  propertyName VARCHAR(180) NULL,
  confirmationCode VARCHAR(120) NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  categoryId CHAR(36) NULL,
  categoryName VARCHAR(120) NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
  status VARCHAR(40) NOT NULL DEFAULT 'New',
  assignedTo VARCHAR(160) NULL,
  confidence FLOAT NOT NULL DEFAULT 0,
  decisionType VARCHAR(40) NOT NULL DEFAULT 'review',
  flagReason TEXT NULL,
  dedupeKey VARCHAR(255) NULL,
  conversationSnippet TEXT NULL,
  messageIds JSON NULL,
  sourceMeta JSON NULL,
  notificationTargets JSON NULL,
  lastDetectedAt DATETIME NULL,
  approvedAt DATETIME NULL,
  rejectedAt DATETIME NULL,
  resolvedAt DATETIME NULL,
  createdBy VARCHAR(120) NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_action_item_beta_items_reservationId (reservationId),
  INDEX idx_action_item_beta_items_listingId (listingId),
  INDEX idx_action_item_beta_items_categoryId (categoryId),
  INDEX idx_action_item_beta_items_status (status),
  INDEX idx_action_item_beta_items_dedupeKey (dedupeKey)
);

CREATE TABLE IF NOT EXISTS action_item_beta_settings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  settingKey VARCHAR(120) NOT NULL UNIQUE,
  value JSON NOT NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
