CREATE TABLE IF NOT EXISTS ll_buddy_suggestions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  reservationId INT NULL,
  listingId INT NULL,
  communicationId CHAR(36) NULL,
  guestName VARCHAR(160) NULL,
  propertyName VARCHAR(180) NULL,
  guestMessage TEXT NOT NULL,
  suggestedReply TEXT NOT NULL,
  internalSummary TEXT NULL,
  confidence FLOAT NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
  autoSendAllowed TINYINT(1) NOT NULL DEFAULT 0,
  sourceReferences JSON NULL,
  warnings JSON NULL,
  promptVersion VARCHAR(120) NOT NULL DEFAULT 'll-buddy-v1',
  model VARCHAR(120) NOT NULL DEFAULT 'rules-first',
  dedupeKey VARCHAR(255) NULL,
  createdBy VARCHAR(120) NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_suggestions_reservationId (reservationId),
  INDEX idx_ll_buddy_suggestions_listingId (listingId),
  INDEX idx_ll_buddy_suggestions_communicationId (communicationId),
  INDEX idx_ll_buddy_suggestions_status (status)
);

CREATE TABLE IF NOT EXISTS ll_buddy_conversations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  externalConversationId VARCHAR(255) NULL,
  sourceSystem VARCHAR(60) NOT NULL DEFAULT 'local',
  channel VARCHAR(60) NULL,
  guestName VARCHAR(160) NULL,
  listingId INT NULL,
  propertyName VARCHAR(180) NULL,
  reservationId INT NULL,
  lastMessageAt DATETIME NULL,
  lastInboundMessageAt DATETIME NULL,
  lastOutboundMessageAt DATETIME NULL,
  unread TINYINT(1) NOT NULL DEFAULT 0,
  unresponded TINYINT(1) NOT NULL DEFAULT 0,
  assignedUserId VARCHAR(160) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'open',
  syncStatus VARCHAR(40) NOT NULL DEFAULT 'synced',
  lastSyncedAt DATETIME NULL,
  syncError TEXT NULL,
  lastMessagePreview TEXT NULL,
  metadata JSON NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_conversations_external (externalConversationId),
  INDEX idx_ll_buddy_conversations_source (sourceSystem),
  INDEX idx_ll_buddy_conversations_listingId (listingId),
  INDEX idx_ll_buddy_conversations_reservationId (reservationId),
  INDEX idx_ll_buddy_conversations_status (status)
);

CREATE TABLE IF NOT EXISTS ll_buddy_messages (
  id CHAR(36) NOT NULL PRIMARY KEY,
  conversationId CHAR(36) NOT NULL,
  externalMessageId VARCHAR(255) NULL,
  sourceSystem VARCHAR(60) NOT NULL DEFAULT 'local',
  channel VARCHAR(60) NULL,
  direction VARCHAR(20) NOT NULL,
  senderType VARCHAR(30) NOT NULL DEFAULT 'unknown',
  senderName VARCHAR(160) NULL,
  senderExternalId VARCHAR(160) NULL,
  securestayUserId VARCHAR(120) NULL,
  body TEXT NOT NULL,
  attachments JSON NULL,
  sentAt DATETIME NULL,
  receivedAt DATETIME NULL,
  sendStatus VARCHAR(40) NOT NULL DEFAULT 'received',
  rawPayload JSON NULL,
  sourceCommunicationId CHAR(36) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_messages_conversationId (conversationId),
  INDEX idx_ll_buddy_messages_external (externalMessageId),
  INDEX idx_ll_buddy_messages_direction (direction),
  INDEX idx_ll_buddy_messages_sendStatus (sendStatus)
);

CREATE TABLE IF NOT EXISTS ll_buddy_generated_items (
  id CHAR(36) NOT NULL PRIMARY KEY,
  itemType VARCHAR(30) NOT NULL,
  reservationId INT NULL,
  listingId INT NULL,
  guestName VARCHAR(160) NULL,
  propertyName VARCHAR(180) NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  categoryName VARCHAR(120) NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
  status VARCHAR(40) NOT NULL DEFAULT 'New',
  confidence FLOAT NOT NULL DEFAULT 0,
  proposedResolution TEXT NULL,
  flagReason TEXT NULL,
  messageIds JSON NULL,
  sourceReferences JSON NULL,
  dedupeKey VARCHAR(255) NULL,
  createdBy VARCHAR(120) NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_generated_items_type (itemType),
  INDEX idx_ll_buddy_generated_items_reservationId (reservationId),
  INDEX idx_ll_buddy_generated_items_listingId (listingId),
  INDEX idx_ll_buddy_generated_items_status (status)
);

CREATE TABLE IF NOT EXISTS ll_buddy_feedback (
  id CHAR(36) NOT NULL PRIMARY KEY,
  suggestionId CHAR(36) NULL,
  rating VARCHAR(40) NOT NULL,
  finalReply TEXT NULL,
  notes TEXT NULL,
  tags JSON NULL,
  createdBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_feedback_suggestionId (suggestionId)
);

CREATE TABLE IF NOT EXISTS ll_buddy_learning_candidates (
  id CHAR(36) NOT NULL PRIMARY KEY,
  candidateType VARCHAR(40) NOT NULL,
  listingId INT NULL,
  propertyName VARCHAR(180) NULL,
  topic VARCHAR(120) NOT NULL,
  proposedText TEXT NOT NULL,
  reason TEXT NULL,
  confidence FLOAT NOT NULL DEFAULT 0,
  evidenceCount INT NOT NULL DEFAULT 1,
  evidence JSON NULL,
  warnings JSON NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  decisionReason TEXT NULL,
  reviewedBy VARCHAR(120) NULL,
  reviewedAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_learning_listingId (listingId),
  INDEX idx_ll_buddy_learning_status (status)
);

CREATE TABLE IF NOT EXISTS ll_buddy_audit_logs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  eventType VARCHAR(80) NOT NULL,
  entityType VARCHAR(80) NULL,
  entityId VARCHAR(80) NULL,
  summary TEXT NULL,
  details JSON NULL,
  createdBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ll_buddy_audit_eventType (eventType)
);
