CREATE TABLE IF NOT EXISTS guest_analysis_settings (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  settingKey VARCHAR(120) NOT NULL UNIQUE,
  value JSON NOT NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS guest_analysis_settings_audit (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  settingKey VARCHAR(120) NOT NULL,
  previousValue JSON NOT NULL,
  nextValue JSON NOT NULL,
  migrationPlan JSON NULL,
  updatedBy VARCHAR(120) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
